### ISSUE TITLE
Support Azure Container Registry

### ISSUE THREAD

**Issue by tomoyamachi** [goodwithtech/dockle#199]
https://github.com/goodwithtech/dockle/issues/195
https://github.com/goodwithtech/dockle/issues/198

**Comment by olafurnielsen** [comment]
I'm using GitHub Actions and using `azure/docker-login` with service principal auth prior to Dockle and that works fine when referencing a remote image in ACR. Maybe there's a similar action ADO users could take (#195 #198).

But an implementation for ACR similar to what you have for AWS and GCP would be nice.

```
    steps:
      - name: Logon to Azure ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ vars.ACR_REGISTRY }}
          username: ${{ secrets.ACR_SERVICEPRINCIPAL }}
          password: ${{ secrets.ACR_SERVICEPRINCIPAL_PASSWORD }}

      - name: Run Dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: '${{ vars.ACR_REGISTRY }}/<your_image>:${{ needs.build.outputs.version }}'
```
