### ISSUE TITLE
Is there an official GitHub Action for Dockle?

### ISSUE THREAD

**Issue by loganmarchione** [goodwithtech/dockle#209]
I was using Azure's [container-scan](https://github.com/Azure/container-scan) GitHub Action (which runs Dockle), but it was recently deprecated. 

When I search, I see a bunch of unofficial Actions.
https://github.com/marketplace?type=actions&query=dockle

Is there an official Action?

**Comment by loganmarchione** [comment]
For anyone who finds this, here is what I'm using:

```
    - name: Container scan with Dockle
      uses: docker://goodwithtech/dockle:v0.4.9
      with:
        args: '--exit-code 1 --format list ${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}'
```
